blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/LumexUI/lumexui/discussions/new?category=help
    about: ğŸ™ If you can't get something to work the way you expect, ask for help in our discussion forums.
  - name: Discord Community
    url: https://discord.gg/e2QNPByQ
    about: ğŸ’¬ Ask quick questions or simply chat on the LumexUI community Discord server.
